services:
  - type: web
    name: ncaa-all-sports
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir app main:run
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: DB_PATH
        value: /tmp/ncaa.db
      - key: NCAA_SCHEDULE_URL
        sync: false
      - key: NCAA_SCHEDULE_API_KEY
        sync: false
      - key: ESPN_SCHEDULE_URL
        sync: false
      - key: ESPN_SCHEDULE_API_KEY
        sync: false
      - key: OFFICIAL_SCHEDULE_URL
        sync: false
      - key: OFFICIAL_SCHEDULE_API_KEY
        sync: false
