services:
  - type: web
    name: ncaa-all-sports
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    autoDeploy: true
    envVars:
      - key: REFRESH_MINUTES
        value: "15"
      - key: LOOKAHEAD_DAYS
        value: "7"
