let range="today",allEvents=[];
const sportColors={Football:"#f1c40f",Soccer:"#2ecc71",Basketball:"#e67e22",Volleyball:"#8e44ad",Baseball:"#e74c3c",Softball:"#ff69b4","Ice Hockey":"#3498db","Field Hockey":"#8b5a2b","Track & Field":"#5dade2","Swimming & Diving":"#17c0d4"};
const $=x=>document.querySelector(x);
async function loadSports(){let x=await fetch("/api/sports").then(r=>r.json()); for(let s in x){let o=document.createElement("option");o.value=s;o.textContent=s;$("#sport").appendChild(o)}}
function bounds(){let n=new Date();let d=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()));if(range==="yesterday")return [new Date(d-864e5),d];if(range==="tomorrow")return [new Date(+d+864e5),new Date(+d+2*864e5)];if(range==="next7")return [new Date(+d+2*864e5),new Date(+d+9*864e5)];return [d,new Date(+d+864e5)]}
async function load(){let r=await fetch("/api/events?days=10").then(r=>r.json());let [a,b]=bounds(),q=$("#search").value.toLowerCase(),sp=$("#sport").value;
allEvents=r.events.filter(e=>{let d=new Date(e.start_utc);return d>=a&&d<b&&(!sp||e.sport===sp)&&(!q||JSON.stringify(e).toLowerCase().includes(q))});render()}
function render(){let f=$("#feed");f.innerHTML="";let days={};for(let e of allEvents){let k=e.start_utc.slice(0,10);(days[k]??=[]).push(e)}Object.keys(days).sort().forEach(day=>{let h=document.createElement("div");h.className="day";h.textContent=day+" UTC";f.appendChild(h);days[day].forEach(e=>{let x=document.createElement("article");x.className="event";x.innerHTML=`<div class="time">${new Date(e.start_utc).toISOString().slice(11,16)} UTC</div><div class="stripe" style="background:${sportColors[e.sport]||"#aaa"}></div><div class="teams"><b>${e.home}</b><b>${e.away}</b><div class="meta">${e.sport} • ${e.competition} • ${e.venue||"Venue TBD"}</div></div><div class="status">${e.status}</div>`;x.onclick=()=>detail(e);f.appendChild(x)})})}
function detail(e){$("#detail").innerHTML=`<h2>${e.home} vs ${e.away}</h2><div class="kv"><b>Sport</b><span>${e.sport}</span></div><div class="kv"><b>UTC</b><span>${new Date(e.start_utc).toISOString().replace("T"," ").slice(0,16)}</span></div><div class="kv"><b>Competition</b><span>${e.competition}</span></div><div class="kv"><b>Status</b><span>${e.status}</span></div><div class="kv"><b>Venue</b><span>${e.venue||"TBD"}</span></div><div class="kv"><b>Sources</b><span>${(e.sources||[]).join(", ")}</span></div><div class="kv"><b>Confidence</b><span>${Math.round((e.confidence||0)*100)}%</span></div>`;$("#modal").classList.remove("hidden")}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");range=b.dataset.range;load()});
$("#search").oninput=load;$("#sport").onchange=load;$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.add("hidden")};
setInterval(()=>$("#clock").textContent=new Date().toISOString().replace("T"," ").slice(0,19)+" UTC",1000);
loadSports().then(load);
